"""empty message

Revision ID: 0a93cc4864ea
Revises: 26414837bc3d
Create Date: 2024-11-01 01:21:04.014220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a93cc4864ea'
down_revision = '26414837bc3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('username', sa.String(), nullable=False))
    op.drop_column('Users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('email', sa.VARCHAR(), nullable=False))
    op.drop_column('Users', 'username')
    # ### end Alembic commands ###
