"""empty message

Revision ID: 25486682f0e4
Revises: de37c77a8fc4
Create Date: 2024-11-02 15:54:26.638261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25486682f0e4'
down_revision = 'de37c77a8fc4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('email', sa.String(), nullable=False))
    op.drop_column('Users', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('is_admin', sa.BOOLEAN(), nullable=True))
    op.drop_column('Users', 'email')
    # ### end Alembic commands ###
