"""empty message

Revision ID: 26414837bc3d
Revises: d0c08b98c95c
Create Date: 2024-11-01 00:47:15.891627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26414837bc3d'
down_revision = 'd0c08b98c95c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Users_id'), 'Users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Users_id'), table_name='Users')
    # ### end Alembic commands ###
