"""empty message

Revision ID: 3e8b4789fe64
Revises: 0a93cc4864ea
Create Date: 2024-11-01 01:28:26.413335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e8b4789fe64'
down_revision = '0a93cc4864ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Cars_id'), 'Cars', ['id'], unique=False)
    op.create_index(op.f('ix_Orders_id'), 'Orders', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Orders_id'), table_name='Orders')
    op.drop_index(op.f('ix_Cars_id'), table_name='Cars')
    # ### end Alembic commands ###
