"""Message describing migration

Revision ID: 876af7c753d2
Revises: 
Create Date: 2024-10-31 16:03:19.705296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '876af7c753d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Orders')
    op.drop_table('Users')
    op.add_column('Cars', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('Cars', 'car_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cars', sa.Column('car_id', sa.INTEGER(), nullable=False))
    op.drop_column('Cars', 'id')
    op.create_table('Users',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('surname', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('Orders',
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('order_id', 'user_id')
    )
    # ### end Alembic commands ###
