"""empty message

Revision ID: d0c08b98c95c
Revises: 1ef0c3c63197
Create Date: 2024-10-31 21:30:58.145462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0c08b98c95c'
down_revision = '1ef0c3c63197'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'surname')
    op.drop_column('Users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('name', sa.VARCHAR(), nullable=False))
    op.add_column('Users', sa.Column('surname', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
