"""empty message

Revision ID: e15023d82bf5
Revises: 25486682f0e4
Create Date: 2024-11-03 12:10:05.481161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e15023d82bf5'
down_revision = '25486682f0e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Orders', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'Orders', 'Users', ['user_id'], ['id'])
    op.add_column('Users', sa.Column('password_hash', sa.Text(), nullable=True))
    op.alter_column('Users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'Users', ['username'])
    op.create_unique_constraint(None, 'Users', ['email'])
    op.drop_column('Users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('hashed_password', sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, 'Users', type_='unique')
    op.drop_constraint(None, 'Users', type_='unique')
    op.alter_column('Users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('Users', 'password_hash')
    op.drop_constraint(None, 'Orders', type_='foreignkey')
    op.alter_column('Orders', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
